{
 "title": "DailyData",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "Shards", "query": "*" },
   { "name": "Resources", "query": "${Shards}.*" },
   { "name": "Average_over_days", "query": "1, 5, 10" }
  ]
 },
 "panels": [
  {
   "title": "Daily credit flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(sumSeries(multiplySeriesLists(#A, #C)), $Average_over_days), 'Total')",
     "targetFull": "alias(movingAverage(sumSeries(multiplySeriesLists($Shards.*.volume, $Shards.*.avgPrice)), $Average_over_days), 'Total')"
    }
   ]
  },
  {
   "title": "Daily credit flow per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists(#A, #C), 0, 'sumSeries'), $Average_over_days), 0)",
     "targetFull": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists($Shards.*.volume, $Shards.*.avgPrice), 0, 'sumSeries'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Mean credit flow",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists(#A, #C), 1, 'sumSeries'), $Average_over_days), 0)",
     "targetFull": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists($Shards.*.volume, $Shards.*.avgPrice), 1, 'sumSeries'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Transaction count per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode($Shards.*.transactions, 0, 'sumSeries'), $Average_over_days), 0)"
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Credit flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists(#A, #C), 1, 'sumSeries'), $Average_over_days), 0)",
     "targetFull": "aliasByNode(movingAverage(groupByNode(multiplySeriesLists($Shards.$Resources.volume, $Shards.$Resources.avgPrice), 1, 'sumSeries'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Credit flow per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(groupByNodes(multiplySeriesLists(#A, #C), 'sumSeries', 0, 1), $Average_over_days)), 0, 1)",
     "targetFull": "aliasByNode(removeZeroSeries(movingAverage(groupByNodes(multiplySeriesLists($Shards.$Resources.volume, $Shards.$Resources.avgPrice), 'sumSeries', 0, 1), $Average_over_days)), 0, 1)"
    }
   ]
  },
  {
   "title": "Transaction count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode($Shards.$Resources.transactions, 1, 'sum'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Transaction count per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage($Shards.$Resources.transactions, $Average_over_days)), 0, 1)"
    }
   ]
  },
  {
   "title": "Avgerage price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode($Shards.$Resources.avgPrice, 1, 'averageSeries'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Avgerage price per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage($Shards.$Resources.avgPrice, $Average_over_days)), 0, 1)"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(groupByNode($Shards.$Resources.volume, 1, 'sumSeries'), $Average_over_days), 0)"
    }
   ]
  },
  {
   "title": "Volume per shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage($Shards.$Resources.volume, $Average_over_days)), 0, 1)"
    }
   ]
  }
 ]
}