version: "3"

services:
  nodejs:
    build: .
    restart: unless-stopped
    ports:
      - "10000:10000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screepsMarket.rule=Host(`screepsmarketapi.pandascreeps.com`)"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.screepsMarket.entrypoints=websecure"
      - "traefik.http.routers.screepsMarket.tls.certresolver=letsencrypt"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./dailyFiles:/usr/screepsmarket/dailyFiles"
      - "./completeFiles:/usr/screepsmarket/completeFiles"
      - "./compressedFiles:/usr/screepsmarket/compressedFiles"
      - "./logs:/usr/screepsmarket/logs"
