version: '3'

services:
  nodejs:
    ports:
      - "10000:10000"
    build: .
    restart: unless-stopped
    volumes:
      - "./dailyFiles:dailyFiles"
      - "./completeFiles:completeFiles"
      - "./compressedFiles:compressedFiles"
      - "./logs:logs"
