version: '3'

services:
  nodejs:
    ports:
      - "10000:10000"
    build: .
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./dailyFiles:/usr/screepsmarket/dailyFiles"
      - "./completeFiles:/usr/screepsmarket/completeFiles"
      - "./compressedFiles:/usr/screepsmarket/compressedFiles"
      - "./logs:/usr/screepsmarket/logs"
